### ISSUE TITLE
Requirements not installing

### ISSUE THREAD

**Issue by Aiml3ss** [simse/chronos#3] opened 2019-05-29 14:38 UTC
Hi Simse,

I am trying to install requirements for my script and I can't seem to get the install pip requirements function to work correctly. 

<img width="1076" alt="Screen Shot 2019-05-29 at 8 52 20 AM" src="https://user-images.githubusercontent.com/1891520/58565314-1bce0280-81f4-11e9-8908-fc84a8b8b9fb.png">

You can see in the screenshot I am trying to install pandas and psycopg2. I've tried both just inputting pandas and psycopg2 without the version and from what you see in the screenshot. 

I have this installed via your docker file on the hub, I'm not 100% if that was installed correctly on my unraid server. 

Here is a screenshot of the file structure confirming that its not installing the requirements.txt: 

<img width="331" alt="Screen Shot 2019-05-29 at 9 34 55 AM" src="https://user-images.githubusercontent.com/1891520/58565896-2e950700-81f5-11e9-8cfd-3ddba64ae0f3.png">

Am I an idiot or is there an issue somewhere.

Thanks,
Andrew

**Comment by simse** [comment] 2019-05-29 15:35
Hi Andrew,

I am able to replicate your issue. It would seem that the requirements don't install because the Chronos instance crashes. I will look into it and push and update as quick as possible.

**Comment by simse** [comment] 2019-05-30 23:13
Unfortunately it seems the issue is caused by the _pandas_ library taking a long time to install. Your best bet right now is press the install requirements button, and just let your browser sit until it stops spinning. I've checked and it does eventually install. Unfortunately I'm on holiday right now, but as soon as I get back, I'll push and update to make long Pip installations a bit more smooth.

**Comment by Aiml3ss** [comment] 2019-06-02 15:31
I tried it out again per your advice above, I still get the same error with pandas module not being installed. Maybe my chronos instance crashes before it can install, it seems like pandas sometimes install really really slowly in certain circumstances. No rush on the update! Appreciate you being so responsive, you rock!

**Comment by crimsdings** [comment] 2019-12-10 11:39
i am also unable to install python-telegram-bot with the requirements - however i get the green positive message - but the installation fails

**Comment by simse** [comment] 2019-12-10 22:37
This issue should be fixed by the latest update. Please try updating and checking back.

**Closed** 2020-01-14 02:28 UTC
Labels: bug
